- name: "type: feature"
  color: "1D76DB"
  description: "New feature or enhancement"
- name: "type: fix"
  color: "D73A4A"
  description: "Bug fix or regression"
- name: "type: chore"
  color: "6A737D"
  description: "Maintenance, refactor, or tooling"
- name: "type: release"
  color: "0E8A16"
  description: "Release planning and tracking"
- name: "type: hotfix"
  color: "B60205"
  description: "Emergency fix for production"
- name: "area: frontend"
  color: "A2EEEF"
  description: "Next.js UI and client-side code"
- name: "area: backend"
  color: "D4C5F9"
  description: "Django REST Framework services"
- name: "area: api"
  color: "C5DEF5"
  description: "API design, contracts, and schemas"
- name: "area: database"
  color: "FEF2C0"
  description: "Schema, migrations, and data"
- name: "area: ci-cd"
  color: "F9D0C4"
  description: "CI/CD pipelines, infrastructure, and DevOps"
- name: "area: docs"
  color: "BFDADC"
  description: "Documentation and developer guides"
- name: "priority: P0"
  color: "B60205"
  description: "Critical: immediate attention required"
- name: "priority: P1"
  color: "D93F0B"
  description: "High: prioritize next"
- name: "priority: P2"
  color: "FBCA04"
  description: "Medium: schedule accordingly"
- name: "priority: P3"
  color: "0E8A16"
  description: "Low: nice-to-have"
- name: "status: triage"
  color: "FEF2C0"
  description: "Needs triage (scope, priority, owner)"
- name: "status: ready"
  color: "C2E0C6"
  description: "Ready for implementation"
- name: "status: in-progress"
  color: "1D76DB"
  description: "Actively being worked on"
- name: "status: blocked"
  color: "B60205"
  description: "Blocked by dependency or decision"
- name: "status: review"
  color: "5319E7"
  description: "Awaiting review (PR / feedback)"
- name: "status: done"
  color: "0E8A16"
  description: "Completed; awaiting QA/verification"
